### ISSUE TITLE
Missing password validation

### ISSUE THREAD

**Issue by noorhammodi** [jasonhillinger/Mini-Stackoverflow#17]
Add code that verifies the password input and rejects password if incorrect.
Links to [ User story #1](https://github.com/jasonhillinger/soen341project/issues/18 )

**Comment by jonman5** [comment]
We will implement this in PHP, once some of the html is done we will combine it.

**Comment by jonman5** [comment]
Commit [e7108e3](https://github.com/jasonhillinger/soen341project/commit/e7108e37d4b1bd10bf64796696c22e72406ff1f1) closes this issue.
